# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 15:28
from __future__ import unicode_literals

import codenerix.fields
import codenerix.lib.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codenerix_geodata', '0002_auto_20170921_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias')),
                ('town', models.CharField(blank=True, max_length=250, null=True, verbose_name='Town')),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Zip code')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone')),
                ('nid', models.CharField(blank=True, max_length=20, verbose_name='NID')),
                ('business_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Business name')),
                ('digital_sign', codenerix.fields.ImageAngularField(blank=True, max_length=200, null=True, upload_to=codenerix.lib.helpers.upload_path, verbose_name='Digital sign')),
                ('name_file_sign', models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file digital sign')),
                ('company_seal', codenerix.fields.ImageAngularField(blank=True, max_length=200, null=True, upload_to=codenerix.lib.helpers.upload_path, verbose_name='Company seal')),
                ('name_file_seal', models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file company seal')),
                ('company_logo', codenerix.fields.ImageAngularField(blank=True, max_length=200, null=True, upload_to=codenerix.lib.helpers.upload_path, verbose_name='Company logo')),
                ('name_file_logo', models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file company logo')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codenerix_corporate_corporateimage_geo_addresses', to='codenerix_geodata.City', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codenerix_corporate_corporateimage_geo_addresses', to='codenerix_geodata.Country', verbose_name='Country')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codenerix_corporate_corporateimage_geo_addresses', to='codenerix_geodata.Province', verbose_name='Province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codenerix_corporate_corporateimage_geo_addresses', to='codenerix_geodata.Region', verbose_name='Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
