# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_corporate', '0002_remove_corporateimage_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporateimage',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
    ]
