# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_corporate', '0003_auto_20171128_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateimage',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
